earth:
  stage: /tmp/staging
  # Ingest Server to connect with
  ingest:
    endpoint: https://localhost:8080
    username: admin
    password: example-password
    node: uscd-dpn
  # DPN RESTful servers to connect to
  dpn:
    local:
      auth-key: my-auth-key
      api-root: https://my-api/
      name: chron
    remote:
    -
     auth-key: example-auth-key
     api-root: https://example-dpn-node.edu
     name: example-dpn-node
  # Cron based triggers
  cron:
    replicate: '0 0 * * * *'
  hikari:
    url: jdbc:h2:./db/intake

spring.profiles.active: production

# Disable any type of DB support
spring.data.jpa.repositories.enabled: false

server.port: 9000

logging:
  path: /var/log/dpn/
  file: dpn.log
  level:
    org.chronopolis: TRACE
